### ISSUE TITLE
COLLEGE INSIDER - PAYMENT IS NOT WORKING

### ISSUE THREAD

**Issue by mohamedashic** [IlahiTechnologies/bugs-to-fix#205]
PAYMENT IS NOT WORKING FOR THE COLLEGE INSIDER APP
ITS CRITICAL KINDLY DO THE NEEDFUL

**Comment by mohamedashic** [comment]
@SasiZets Kindly look into it its waiting for your perusal

**Comment by SasiZets** [comment]
Hi, that is issue is nothing to do with the code. everything is fine. its just the payment is denied from that card.
